# Generated by Django 2.2 on 2020-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
